### ISSUE TITLE
Códigos com alguns erros...

### ISSUE THREAD

**Issue by luizhtss** [heroslender/HeroStackDrops#1]
Olá, tentei compilar o código, porém estava com alguns erros de sintaxe (construtores não definidos, ou sem parametros, etc..)

**Comment by heroslender** [comment]
Compilaste com o maven?

**Comment by luizhtss** [comment]
Sim.

**Comment by heroslender** [comment]
Pelo que dizes, parece ser algum problema com o lombok, mas não devia dar erro ao correr o maven. Manda alguns dos erros só para confirmar.

**Comment by luizhtss** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/28742028/63228779-7b71f380-c1ce-11e9-8b6a-b5575297c461.png)

**Comment by luizhtss** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/28742028/63228782-8a58a600-c1ce-11e9-874f-ba562900a0e5.png)

**Comment by heroslender** [comment]
É, problema com o lombok, tens instalar no eclipse o plugin.

Transfere a jar dele [lombok-1.18.4.jar](https://search.maven.org/remotecontent?filepath=org/projectlombok/lombok/1.18.4/lombok-1.18.4.jar) e executas com o comando `java -jar lombok-1.18.4.jar`. Irá abrir um GUI onde selecionas o eclipse e instalas.
![Lombok instalo gui](https://www.baeldung.com/wp-content/uploads/2019/01/lombok6.png)

Depois disso é só reiniciar o eclipse que já deve tar.

**Comment by luizhtss** [comment]
Resolvido! muito obrigado!
